services:
  app:
    image: web3lotttery143/web3-lottery-api:latest
    container_name: web3-lottery-api
    env_file:
     - .env
    ports:
     - 3007:3000
    volumes:
     - /var/www/html/web3-lottery-api/.env:/usr/src/app/.env
  